@startuml DocumentModel

hide empty members

class "MedComEkgRecordingBundle" as document <<MedComDocumentBundle>>
class "MedComEkgRecordingComposition" as composition <<MedComDocumentComposition>>
class "MedComDocumentOrganization" as organization <<MedComCoreOrganization>>
class "MedComDocumentPractitioner" as practitioner <<MedComCorePractitioner>>
class "MedComDocumentPractitionerRole" as practitionerrole <<MedComCorePractitionerRole>>
class "MedComDocumentPatient" as patient <<DkCorePatient>>
class "MedComEkgObservation" as observation <<MedComCoreCondition>>
   
document -- composition : "entry"
composition -- practitioner : "author:person"
composition -- practitionerrole : "author:person"
composition -- organization : "author:organization"
composition -- patient : "subject"
composition -- observation : "section.entry"
observation -- patient : "subject"
observation -- organization : "performer"
practitionerrole -- practitioner: "practitioner"
practitionerrole -- organization: "organization"

@enduml