id: medcom.fhir.dk.ekg
canonical: http://medcomfhir.dk/ig/ekg
name: DKMedComEKG
title: DK MedCom EKG
description: The DK MedCom IG for EKG
status: active # draft | active | retired | unknown
version: 2.0.0-trial-use
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2026+
releaseLabel: trial-use # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: http://www.medcom.dk
  email: fhir@medcom.dk

dependencies:
  medcom.fhir.dk.xdsmetadata: 1.0.1
  medcom.fhir.dk.terminology: 2.0.2
  medcom.fhir.dk.document: 2.0.0
  medcom.fhir.dk.core: 4.0.0
  hl7.fhir.dk.core: 3.5.0
  hl7.fhir.extensions.r5: 4.0.1
 # ihe.iti.mhd: 4.2.3 //Only used for DocumentReference at the moment
 # hl7.fhir.uv.extensions.r4: 5.2.0

parameters:
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true
    
menu:
  Home: index.html
  Profiles: profiles.html
  Examples: examples.html
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

instanceOptions:
  manualSliceOrdering: true # true | false