Alias: $loinc = http://loinc.org
Alias: $PlrTypeCode = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-dk-ihe-plr-typecode-VS
Alias: $PlrHomeCommunityID = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-ihe-core-homeCommunityId-VS
Alias: $PlrFormatCode = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-ihe-plr-formatcode-VS
Alias: $PlrContentType = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-ihe-core-mimetype-VS
Alias: $ClassCodeCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-classcode-CS
Alias: $TypeCodeCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-LOINC-typecode-CS
Alias: $ContentTypeCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-mimeType-CS
Alias: $LanguageCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-LanguageCode-CS
Alias: $FormatCodeCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-formatcode-CS
Alias: $EventCodeCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-episodeOfCare-CS
Alias: $FacilityTypeCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-snomed-CS
Alias: $PracticeSettingCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-snomed-CS
Alias: $HomeCommunityIDCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-homeCommunityId-CS
Alias: $StatusCS = http://hl7.org/fhir/document-reference-status
Alias: $DanishiheOID = urn:oid:1.2.208.184.100.9
//Alias: $SnomedctOID = urn:oid:2.16.840.1.113883.6.96
//Alias: $LoincOID = urn:oid:2.16.840.1.113883.6.1
//Alias: $MedComOID = urn:oid:1.2.208.184.100.1
//Alias: $SKSOID = urn:oid:1.2.208.176.2.4
//Alias: $NPUOID = urn:oid:1.2.208.176.2.1
//Alias: $PROdkOID = urn:oid:1.2.208.176.7.3.1
//Alias: $MedComFormatOID = urn:oid:1.2.208.184.100.10
//Alias: $DanishxdsOID = urn:oid:1.2.208.176.8.1
//Alias: $IANALanguageOID = urn:oid:2.16.840.1.113883.6.121
//Alias: $IANAMediaOID = urn:oid:2.16.840.1.113883.5.79
Alias: $clinical-status = http://terminology.hl7.org/CodeSystem/condition-clinical
Alias: $category = http://terminology.hl7.org/CodeSystem/condition-category
Alias: $sct = http://snomed.info/sct
Alias: $Mimetypes = http://medcomfhir.dk/ig/terminology/ValueSet/medcom-core-attachmentMimeTypes
Alias: $ClassCodeVS = http://medcomfhir.dk/ig/xdsmetadata/ValueSet/MedCom-ihe-core-classcode-VS
Alias: $ClassCodeCS = http://medcomfhir.dk/ig/xdsmetadata/CodeSystem/MedCom-ihe-classcode-CS
Alias: $obligation = http://hl7.org/fhir/StructureDefinition/obligation
Alias: $PractitionerRole = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-core-PractitionerRolesSKSadministrativ
Alias: $ObsStatusCodeSystem = http://hl7.org/fhir/observation-status
Alias: $MedComObsExtValueAttachment = http://medcomfhir.dk/ig/core/StructureDefinition/medcom-observation-value-attachment-extension

Alias: $DanishXdsOID = urn:oid:1.2.208.184.100.9
//Alias: $DanishiheOID = urn:oid:1.2.208.184.100.9
Alias: $SnomedctOID = http://snomed.info/sct|http://snomed.info/sct/554471000005108 //urn:oid:2.16.840.1.113883.6.96
Alias: $LoincOID = http://loinc.org //urn:oid:2.16.840.1.113883.6.1
Alias: $MedComOID = urn:oid:1.2.208.184.100.1
Alias: $SKSOID = urn:oid:1.2.208.176.2.4
//Alias: $SKSOID = https://www.esundhed.dk/Registre/Landspatientregisteret
//Alias: $SKSOID = http://dk.ehealth.sundhed.fhir.ig.core1
Alias: $NPUOID = urn:oid:1.2.208.176.2.1
Alias: $PROdkOID = urn:oid:1.2.208.176.7.3.1
Alias: $MedComFormatOID = urn:oid:1.2.208.184.100.10
Alias: $DanishHomeCommunityOID = urn:oid:1.2.208.176.8.1
//Alias: $IANALanguageOID = urn:oid:2.16.840.1.113883.6.121
//Alias: $IANALanguageOID = https://www.iana.org/assignments/language-subtag-registry
Alias: $IANALanguageOID = urn:ietf:bcp:47 //urn:oid:2.16.840.1.113883.6.121
Alias: $IANAMediaOID = urn:ietf:bcp:13 //http://terminology.hl7.org/CodeSystem/v3-mediaType //urn:oid:2.16.840.1.113883.5.79
Alias: $HL7 = http://terminology.hl7.org/CodeSystem/v3-Confidentiality //urn:oid:2.16.840.1.113883.5.25
Alias: $hoer = urn:ad:dk:medcom:noah:action-categories
Alias: $DanishPrimaryHealthcareDomainOID = urn:oid:1.2.208.193.100